"""create code_chunks table

Revision ID: 3e5dfbc359f9
Revises: 
Create Date: 2026-07-02 14:00:25.265106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '3e5dfbc359f9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repo_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('chunk_type', sa.String(length=50), nullable=False),
    sa.Column('symbol_name', sa.String(length=255), nullable=True),
    sa.Column('parent_symbol', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('start_line', sa.Integer(), nullable=True),
    sa.Column('end_line', sa.Integer(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_chunks_file_path'), 'code_chunks', ['file_path'], unique=False)
    op.create_index(op.f('ix_code_chunks_repo_name'), 'code_chunks', ['repo_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_code_chunks_repo_name'), table_name='code_chunks')
    op.drop_index(op.f('ix_code_chunks_file_path'), table_name='code_chunks')
    op.drop_table('code_chunks')
    # ### end Alembic commands ###
