"""add pending_actions table for human approval gate

Revision ID: f9caefb99520
Revises: 3e5dfbc359f9
Create Date: 2026-07-03 00:04:24.900565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9caefb99520'
down_revision: Union[str, None] = '3e5dfbc359f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repo_name', sa.String(length=255), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('source_title', sa.String(length=1024), nullable=True),
    sa.Column('source_body', sa.Text(), nullable=True),
    sa.Column('source_diff', sa.Text(), nullable=True),
    sa.Column('agent_output', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewer_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_actions_repo_name'), 'pending_actions', ['repo_name'], unique=False)
    op.create_index(op.f('ix_pending_actions_status'), 'pending_actions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pending_actions_status'), table_name='pending_actions')
    op.drop_index(op.f('ix_pending_actions_repo_name'), table_name='pending_actions')
    op.drop_table('pending_actions')
    # ### end Alembic commands ###
